apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
      description: The Git repository URL
    - name: branch
      type: string
      description: The branch to build
      default: main
    - name: app-name
      type: string
      description: Application name
    - name: build-image
      type: string
      description: The image to build and deploy

  workspaces:
    - name: output

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - cleanup
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: output

    - name: eslint
      taskRef:
        name: eslint
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: output

    - name: jest-test
      taskRef:
        name: jest-test
      runAfter:
        - eslint
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - jest-test
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    # - name: deploy
    #   taskRef:
    #     name: openshift-client
    #     kind: ClusterTask
    #   runAfter:
    #     - buildah
    #   params:
    #     - name: SCRIPT
    #       value: |
    #         oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -